export default{
    PRODUCT_TO_BE_ADDED_TO_CART: "#tbodyid > div:nth-child(1) h4 > a",
    ADD_TO_CART_BUTTON: "#tbodyid a",
    CART_LINK: "#cartur",
    CART_PRODUCTS_TITLE: ".col-lg-8 > h2",
    CART_TOTAL_TITLE: ".col-lg-1 > h2",
    CART_TOTAL_PRICE: "#totalp",
    CART_FIRST_PRODUCT_ADDED: "#tbodyid > tr > td:nth-child(2)",
    CART_DELETE_LINK: "#tbodyid > tr > td:nth-child(4) > a",
    CART_PLACE_ORDER_BUTTON: "div.col-lg-1 > button",
    PLACE_ORDER_TITLE: "#orderModalLabel",
    PLACE_ORDER_NAME: "#name",
    PLACE_ORDER_CREDIT_CARD: "#card",
    PURCHASE_BUTTON: "#orderModal button.btn.btn-primary",
    PURCHASE_MESSAGE: ".sweet-alert > h2",
    PURCHASE_OK_BUTTON: ".confirm",
}
